import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:intl/intl.dart';
import '../models/transaction_model.dart';
import '../models/income_record_model.dart';
import '../models/expense_record_model.dart';

class ReportService {
  /// Generate and print/share PDF report
  Future<void> generateTransactionReport(
    List<MoneyTransaction> transactions,
    List<IncomeRecord> incomeRecords,
    List<ExpenseRecord> expenseRecords,
    String dateRange,
    String typeFilter,
  ) async {
    print(
        'Generating PDF report for ${transactions.length} transactions, '
        '${incomeRecords.length} income records, '
        '${expenseRecords.length} expense records');
    try {
      final pdf = pw.Document();
      final now = DateTime.now();
      final dateFormatter = DateFormat('MMM d, yyyy h:mm a');
      final currencyFormatter =
          NumberFormat.currency(symbol: 'ETB ', decimalDigits: 2);

      // Calculate totals
      double totalDistributed = 0;
      double totalReturned = 0;
      double totalPurchased = 0;

      for (var t in transactions) {
        if (t.type == 'distribution')
          totalDistributed += t.amount;
        else if (t.type == 'return')
          totalReturned += t.amount;
        else if (t.type == 'purchase') totalPurchased += t.amount;
      }

      double totalInvestment = 0;
      double totalSales = 0;
      for (var r in incomeRecords) {
        if (r.kind == IncomeKind.investment)
          totalInvestment += r.amount;
        else
          totalSales += r.amount;
      }

      double totalExpenses = 0;
      for (var e in expenseRecords) {
        totalExpenses += e.amount;
      }

      final totalRecords = transactions.length +
          incomeRecords.length +
          expenseRecords.length;

      List<List<String>> rows = [];
      for (var t in transactions) {
        rows.add([
          DateFormat('MMM d, HH:mm').format(t.createdAt),
          t.workerName.isNotEmpty ? t.workerName : 'Unknown',
          t.typeDisplay,
          currencyFormatter.format(t.amount),
        ]);
      }
      for (var r in incomeRecords) {
        rows.add([
          DateFormat('MMM d, HH:mm').format(r.createdAt),
          r.kind == IncomeKind.investment
              ? (r.viewerName ?? 'Investment')
              : (r.saleCategory ?? 'Sale'),
          r.kind == IncomeKind.investment ? 'Investment' : 'Sale',
          currencyFormatter.format(r.amount),
        ]);
      }
      for (var e in expenseRecords) {
        rows.add([
          DateFormat('MMM d, HH:mm').format(e.createdAt),
          e.expenseCategory,
          'Expense',
          currencyFormatter.format(e.amount),
        ]);
      }

      pdf.addPage(
        pw.MultiPage(
          pageFormat: PdfPageFormat.a4,
          footer: (pw.Context context) {
            return pw.Column(
              children: [
                pw.Divider(color: PdfColors.grey300),
                pw.SizedBox(height: 10),
                pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text('Generated by Cofiz Collector App',
                        style:
                            pw.TextStyle(fontSize: 10, color: PdfColors.grey)),
                    pw.Text(
                        'Page ${context.pageNumber} of ${context.pagesCount}',
                        style:
                            pw.TextStyle(fontSize: 10, color: PdfColors.grey)),
                  ],
                ),
              ],
            );
          },
          build: (pw.Context context) {
            return [
              // Header
              pw.Header(
                level: 0,
                child: pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text('Cofiz Collector Report',
                        style: pw.TextStyle(
                            fontSize: 24, fontWeight: pw.FontWeight.bold)),
                    pw.Text(dateFormatter.format(now),
                        style: const pw.TextStyle(fontSize: 12)),
                  ],
                ),
              ),

              pw.SizedBox(height: 20),

              // Filter Info
              pw.Container(
                padding: const pw.EdgeInsets.all(10),
                decoration: pw.BoxDecoration(
                  border: pw.Border.all(color: PdfColors.grey),
                  borderRadius:
                      const pw.BorderRadius.all(pw.Radius.circular(5)),
                ),
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text('Report Criteria',
                        style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                    pw.SizedBox(height: 5),
                    pw.Text('Date Range: $dateRange'),
                    pw.Text('Type Filter: $typeFilter'),
                    pw.Text('Total Records: $totalRecords'),
                  ],
                ),
              ),

              pw.SizedBox(height: 20),

              // Summary Table
              pw.Text('Summary',
                  style: pw.TextStyle(
                      fontSize: 18, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 10),
              pw.Table.fromTextArray(
                headers: [
                  'Distributed',
                  'Returned',
                  'Coffee Purchase',
                  'Investment',
                  'Sales',
                  'Expenses',
                  'Net Flow'
                ],
                data: [
                  [
                    currencyFormatter.format(totalDistributed),
                    currencyFormatter.format(totalReturned),
                    currencyFormatter.format(totalPurchased),
                    currencyFormatter.format(totalInvestment),
                    currencyFormatter.format(totalSales),
                    currencyFormatter.format(totalExpenses),
                    currencyFormatter.format(totalDistributed -
                        totalReturned -
                        totalPurchased +
                        totalInvestment +
                        totalSales -
                        totalExpenses),
                  ]
                ],
                headerStyle: pw.TextStyle(
                    fontWeight: pw.FontWeight.bold, color: PdfColors.white),
                headerDecoration:
                    const pw.BoxDecoration(color: PdfColors.blueGrey800),
                cellAlignment: pw.Alignment.centerRight,
              ),

              pw.SizedBox(height: 20),

              // Transactions Table
              pw.Text('Transactions',
                  style: pw.TextStyle(
                      fontSize: 18, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 10),
              pw.Table.fromTextArray(
                context: context,
                headers: ['Date', 'Name', 'Type', 'Amount'],
                data: rows,
                headerStyle: pw.TextStyle(
                    fontWeight: pw.FontWeight.bold, color: PdfColors.white),
                headerDecoration:
                    const pw.BoxDecoration(color: PdfColors.blueGrey600),
                rowDecoration: const pw.BoxDecoration(
                    border: pw.Border(
                        bottom: pw.BorderSide(color: PdfColors.grey300))),
                cellAlignment: pw.Alignment.centerLeft,
                cellAlignments: {
                  3: pw.Alignment.centerRight,
                },
              ),

              pw.SizedBox(height: 0),
            ];
          },
        ),
      );

      await Printing.layoutPdf(
        onLayout: (PdfPageFormat format) async => pdf.save(),
        name: 'Cofiz_Report_${DateFormat('yyyyMMdd_HHmm').format(now)}',
      );
    } catch (e, stack) {
      print('Error in ReportService: $e');
      print(stack);
      rethrow;
    }
  }
}
